[package]
name = "obj_gen"
version = "0.1.3"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "Code generation for object meshes."


[dependencies]
obj = { path= "../obj/" }
