[package]
name = "obj"
version = "0.1.10"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "A crate for loading object meshes."


[dependencies]
cgwavefront_obj = { version = "1.0.0", git = "https://github.com/lambdaxymox/cgwavefront_obj" }

