[package]
name = "obj"
version = "0.1.8"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"
description = "A crate for loading object meshes."


[dependencies]
wavefront_obj = { git = "https://github.com/lambdaxymox/wavefront-obj" }
